version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  generate-raw-addresses:
    image: techbureau/catapult-tools:gcc-keccak-0.9.2.1
    command: bash -c "/bin-mount/generate-raw-addresses-if-needed 3 /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./build/generated-addresses:/addresses:rw

  store-addresses:
    build: utilities/dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./utilities/bin/ash:/bin-mount
    - ./utilities/ruby:/ruby
    - ./build/generated-addresses:/addresses:rw

  update_vars:
    build: utilities/dockerfiles/ruby-alpine
#    command: ash -c "sleep 100000"
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /usr/share/base/ruby/bin/update_vars.rb && touch /state/update_vars"
    volumes:
    - ./utilities/bin/ash:/bin-mount
    - ./utilities/ruby:/usr/share/base/ruby
    - ./runtime-vars:/usr/share/base/ruby/config
    - ./api-node:/usr/share/base/api-node
    - ./rest-gateway:/usr/share/base/rest-gateway
    - ./build/generated-addresses:/addresses:rw
    - ./state:/state:rw

  ###### running services ###########
  api-node:
    image: techbureau/catapult-server:gcc-keccak-0.9.2.1
    ports:
    - 7900:7900
#    command: bash -c "sleep 1000000"
    command: bash -c "/bin-mount/wait /state/update_vars && /bin/bash /userconfig/startApiServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./api-node/userconfig:/userconfig/
    - ./data/api-node:/data:rw
    - ./state:/state:rw

  api-broker:
    image: techbureau/catapult-server:gcc-keccak-0.9.2.1
#    command: bash -c "sleep 1000000"
    command: bash -c "/bin-mount/wait /state/update_vars && /bin/bash /userconfig/startBroker.sh"
    ports:
    - 7902:7902
    stop_signal: SIGINT
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./api-node/userconfig:/userconfig/
    - ./data/api-node:/data:rw
    - ./state:/state:rw

  db:
    image: mongo
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./data/mongo:/dbdata:rw

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./data/mongo:/dbdata:rw
    - ./mongo/configs/:/userconfig/:ro
    depends_on:
    - db

  rest-gateway:
    image: nemfoundation/catapult-rest-f2-edge:commit-02aeeeb
    command: ash -c "/bin-mount/wait /state/update_vars && npm start resources/rest.json /userconfig/rest.json"
    stop_signal: SIGINT
    ports:
    - "3000:3000"
    volumes:
    - ./rest-gateway/userconfig/:/userconfig/
    - ./utilities/bin/ash:/bin-mount
    - ./state:/state:rw
    depends_on:
    - init-db
    networks:
      default:
        ipv4_address: 172.20.0.9

